## Code to get first 5 sentences the wikipedia article 
def get_info(word):	
	mystr = ""
	if word == 'Laptop':
		str1 = 'A laptop, also called a notebook computer or simply a notebook, is a small, portable personal computer with a "clamshell" form factor, having, typically, a thin LCD or LED computer screen mounted on the inside of the upper lid of the "clamshell" and an alphanumeric keyboard on the inside of the lower lid. The "clamshell" is opened up to use the computer. Laptops are folded shut for transportation, and thus are suitable for mobile use. Its name comes from "lap", as it was deemed to be placed for use on a person\'s lap. Although originally there was a distinction between laptops and notebooks, the former being bigger and heavier than the latter, as of 2014, there is often no longer any difference.\n\n'
		str2 = 'HISTORY - \n The first laptop-sized notebook computer was the Epson HX-20, invented by Suwa Seikosha\'s Yukio Yokozawa in July 1980, introduced at the COMDEX computer show in Las Vegas by Japanese company Seiko Epson in 1981, and released in July 1982.It had an LCD screen, a rechargeable battery, and a calculator-size printer, in a 1.6 kg (3.5 lb) chassis, the size of an A4 notebook.It was described as a "laptop" and "notebook" computer in its patent. From 1983 onward, several new input techniques were developed and included in laptops, including the touchpad (Gavilan SC, 1983), the pointing stick (IBM ThinkPad 700, 1992), and handwriting recognition (Linus Write-Top,[22] 1987).Optical storage, read-only CD-ROM followed by writeable CD and later read-only or writeable DVD and Blu-ray players, became common in laptops early in the 2000s.\n\n'
		str3 = 'HARDWARE - \n Intel, Asus, Compal, Quanta, and some other laptop manufacturers have created the Common Building Block standard for laptop parts to address some of the inefficiencies caused by the lack of standards and inability to upgrade components. Common Hardware parts of a laptop include -\n Display - Most modern laptops feature a 13 inches (33 cm) or larger color active matrix display based on LED lighting with resolutions of 1280×800 (16:10) or 1366×768 (16:9) pixels and above.\n Central processing unit - A laptop\'s central processing unit (CPU) has advanced power-saving features and produces less heat than one intended purely for desktop use.\n Graphical processing unit - On most laptops a graphical processing unit (GPU) is integrated into the CPU to conserve power and space. This was introduced by Intel with the Core i-series of mobile processors in 2010, and similar accelerated processing unit (APU) processors by AMD later that year. \n Memory - Most laptops use SO-DIMM (small outline dual in-line memory module) memory modules, as they are about half the size of desktop DIMMs.[35] They are sometimes accessible from the bottom of the laptop for ease of upgrading, or placed in locations not intended for user replacement. \n Internal storage - Most laptops use 2.5-inch drives, which are a smaller version of a 3.5-inch desktop drive form factor. 2.5-inch HDDs are more compact, power efficient, and produce less heat, while at the same time have a smaller capacity and a slower data transfer rate. Some very compact laptops support even smaller 1.8-inch HDDs. For SSDs, however, these miniaturization-related trade-offs are nonexistent, because SSDs were designed to have a very small footprint. \n Inputs -  A touchpad (also called a trackpad), a pointing stick, or both, are used to control the position of the cursor on the screen, and an integrated keyboard[43] is used for typing. An external keyboard and mouse may be connected using a USB port or wirelessly, via Bluetooth or similar technology. \n Input/output (I/O) ports - On a typical laptop there are several USB ports, an external monitor port (VGA, DVI, HDMI or Mini DisplayPort), an audio in/out port (often in form of a single socket) is common. Battery and power supply \n Docking Station \n Charging Trolleys \n Accessories \n\n '
		str4 = "MANUFACTURERS AND MAKET SHARE - Acer, Apple, Asus, Dell and Lenovo are major manufacturers of Laptops in the industry. Battery-powered portable computers had just 2% worldwide market share in 1986.However, laptops have become increasingly popular, both for business and personal use.The third quarter of 2008 was the first time when worldwide notebook PC shipments exceeded desktops, with 38.6 million units versus 38.5 million units."
		mystr = str1+str2+str3+str4

	if word == 'Chair':
		str1 = 'A mobile phone, cell phone, cellphone, or hand phone, sometimes shortened to simply mobile, cell or just phone, is a portable telephone that can make and receive calls over a radio frequency link while the user is moving within a telephone service area. The radio frequency link establishes a connection to the switching systems of a mobile phone operator, which provides access to the public switched telephone network (PSTN). Modern mobile telephone services use a cellular network architecture, and, therefore, mobile telephones are called cellular telephones or cell phones, in North America. In addition to telephony, 2000s-era mobile phones support a variety of other services, such as text messaging, MMS, email, Internet access, short-range wireless communications (infrared, Bluetooth), business applications, video games, and digital photography. Mobile phones offering only those capabilities are known as feature phones; mobile phones which offer greatly advanced computing capabilities are referred to as smartphones.\n\n'
		str2 = 'HISTORY - A handheld mobile radio telephone service was envisioned in the early stages of radio engineering.The first handheld cellular mobile phone was demonstrated by John F. Mitchell[1][2] and Martin Cooper of Motorola in 1973, using a handset weighing 2 kilograms (4.4 lb).[3] The first commercial automated cellular network (1G) analog was launched in Japan by Nippon Telegraph and Telephone in 1979.\n\n'
		str3 = 'INFRASTRUCTURE - Mobile phones communicate with cell towers that are placed to give coverage across a telephone service area which is divided up into "cells". Each cell uses a different set of frequencies from neighbouring cells, and will typically be covered by 3 towers placed at different locations. The cell towers are usually interconnected to each other and the phone network and the internet by wired connections. Due to bandwidth limitations each cell will have a maximum number of cell phones it can handle at once. The cells are therefore sized depending on the expected usage density, and may be much smaller in cities. In that case much lower transmitter powers are used to avoid broadcasting beyond the cell. As a phone moves around, a phone will "hand off"- automatically disconnect and reconnect to the tower that gives the best reception. Additionally, short-range Wi-Fi infrastructure is often used by smartphones as much as possible as it offloads traffic from cell networks on to local area networks.\n\n'
		str4 = 'HARDWARE - The common components found on all phones are:\nA CPU, the processor of phones.\nA battery, providing the power source for the phone functions.\nAn input mechanism to allow the user to interact with the phone. These are a keypad for feature phones and touch screens for most smartphones.\nA display which echoes the user\'s typing, and displays text messages, contacts, and more.\nSpeakers for sound.\nSIM cards and R-UIM cards.\n\n'
		str5 = 'LEADING MANUFACTURERS - From 1983 to 1998, Motorola was market leader in mobile phones. Nokia was the market leader in mobile phones from 1998 to 2012.[30] In Q1 2012, Samsung surpassed Nokia, selling 93.5 million units as against Nokia\'s 82.7 million units. Samsung has retained its top position since then. In 2017, the top five manufacturers worldwide were Samsung (20.9%), Apple (14.0%), Huawei (9.8%), Oppo (5.7%), and Vivo (6.5%).[31] During Q2 2018, Huawei overtook Apple as the world\'s second-largest phone manufacturer.'
		mystr = str1+str2+str3+str4+str5

	if word == 'Watch':
		str1= "A watch is a timepiece intended to be carried or worn by a person. It is designed to keep working despite the motions caused by the person's activities. A wristwatch is designed to be worn around the wrist, attached by a watch strap or other type of bracelet. A pocket watch is designed for a person to carry in a pocket. The study of timekeeping is known as horology.\n\n"
		str2 = 'HISTORY - Watches evolved from portable spring-driven clocks, which first appeared in 15th century Europe. Watches were not widely worn in pockets until the 17th century. One account says that the word "watch" came from the Old English word woecce which meant "watchman", because it was used by town watchmen to keep track of their shifts at work.Another says that the term came from 17th century sailors, who used the new mechanisms to time the length of their shipboard watches (duty shifts).Drawing of one of his first balance springs, attached to a balance wheel, by Christiaan Huygens, published in his letter in the Journal des Sçavants of 25 February 1675. The application of the spiral balance spring (spiral hairspring) for watches ushered in a new era of accuracy for portable timekeepers, similar to that which the pendulum had introduced for clocks.A great leap forward in accuracy occurred in 1657 with the addition of the balance spring to the balance wheel, an invention disputed both at the time and ever since between Robert Hooke and Christiaan Huygens. This innovation increased watches\' accuracy enormously, reducing error from perhaps several hours per day to perhaps 10 minutes per day, resulting in the addition of the minute hand to the face from around 1680 in Britain and 1700 in France.The British dominated the watch making industry and had major control of the market till the advent of modern watches.\n\n'
		str3 = 'WORKING - Most watches intended mainly for timekeeping today have electronic movements, with mechanical hands on the watch face indicating the time. A mechanical movement uses an escapement mechanism to control and limit the unwinding and winding parts of a spring, converting what would otherwise be a simple unwinding into a controlled and periodic energy release. A mechanical movement also uses a balance wheel together with the balance spring (also known as a hairspring) to control the motion of the gear system of the watch in a manner analogous to the pendulum of a pendulum clock. The tourbillon, an optional part for mechanical movements, is a rotating frame for the escapement, which is used to cancel out or reduce the effects of gravitational bias to the timekeeping. Due to the complexity of designing a tourbillon, they are very expensive, and only found in prestigious watches.\n\n'
		str4 = 'ADDITIONAL FEATURES- Many watches include a variety of features including: \nNavigation \nWater-Proofing \nSpeech Synthesis \nBacklighting'
		mystr = str1+str2+str3+str4
	
	return mystr
	import wikipedia
	mystr = wikipedia.summary(word,sentences = 5)
	return mystr